### ISSUE TITLE
Heading after list without blank line is merged into last list item

### ISSUE THREAD

**Issue by azrdev** [ether/ep_markdown#11]
Create a (numbered or unnumbered) list. Make sure its last item contains some text.
After the list, directly on the next line, enter some text and format it as Heading (no matter what level).
Export as markdown (see #10).
- item1
- item2
# head

---
## Expected result:

```
* item1
* item2
# head
```

(Following [pandoc's markdown](http://pandoc.org/README.html#extension-blank_before_header), there should even be a blank line before the header)
## Actual result

```
* item1
* item2#head
```

The linebreak after the list is removed. This does not happen with normal text.

**Comment by JohnMcLear** [comment]
Confirmed.  Horrible bug.

**Comment by JohnMcLear** [comment]
Try that
