### ISSUE TITLE
How to install? npmjs uses old fork

### ISSUE THREAD

**Issue by tomabrafix** [ether/ep_markdown#119]
How should this plugin be installed/updated?

[npmjs](https://www.npmjs.com/package/ep_markdown) uses not this repo, it uses an [old fork with version `0.1.50`](https://github.com/johnmclear/ep_markdown) (current version should be `0.1.65`). Therefore the installation via `npm install` or via `/admin/plugins` installs the outdated version and not this one.

**Comment by SamTV12345** [comment]
@tomabrafix 0.1.68 is pushed to npmjs. So you should be able to install this plugin.

**Comment by SamTV12345** [comment]
Most likely not. @JohnMcLear can you fix this? It is non critical.

**Comment by JohnMcLear** [comment]
hrm, don't you just need to modify https://github.com/ether/ep_markdown/blob/master/package.json#L12 ?

**Comment by SamTV12345** [comment]
> hrm, don't you just need to modify https://github.com/ether/ep_markdown/blob/master/package.json#L12 ?

Thanks @JohnMcLear . That did the trick 😄 .
