### ISSUE TITLE
Export files with file extension

### ISSUE THREAD

**Issue by rugk** [ether/ep_markdown#16]
It would be nice if the export would add `.md` as the file extension as `.md` is the file extension of markdown.

**Comment by JohnMcLear** [comment]
this would be relatively easy to do, etherpad exposes a method for plugin file name..  

http://etherpad.org/doc/v1.5.7/#index_exportfilename

**Comment by rugk** [comment]
So please do. :yum:

I'm not that experienced in JS/Etherpad programming, so unfortunately I cannot help you.

**Comment by JohnMcLear** [comment]
I'm available as a gun for hire

**Comment by JohnMcLear** [comment]
done
