### ISSUE TITLE
Writing in Markdown mode

### ISSUE THREAD

**Issue by josephernest** [ether/ep_markdown#21]
I tried this:

1. Enable "Show Markdown"

2. Write text in Markdown syntax, for example `**hello** this is markdown`

3. Disable "Show Markdown"

Then the `**hello**` text, that was written during "markdown mode on", is not interpreted as **hello** (in bold). Why? Is this normal behaviour?

Demo: https://annuel.framapad.org/p/dCfecDEfqw

**Comment by pichouk** [comment]
I guess it duplicates #4

**Comment by JohnMcLear** [comment]
I didn't implement this intentionally..  Do people really want this?  It seems like a terrible idea?

**Comment by JohnMcLear** [comment]
Defo a duplicate of #4
