### ISSUE TITLE
Export modifies URL syntax

### ISSUE THREAD

**Issue by eike2013** [ether/ep_markdown#22]
When exporting a pad which contains urls using http://linktopad.com/p/testpad/export/markdown the resulting file contains a wrong syntax.

In ep itself the shown syntax is correct, e.g. like described in this cheatsheet https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links).

`[I'm an inline-style link](https://www.google.com)`

But the exported file wraps an  `\url` tag around the link and corrupting it for further processing, e.g. pelican static site generation.

The code responsible for this is in the exportMarkdown.js
`    if (urls)
    {
      urls.forEach(function (urlData)
      {
        var startIndex = urlData[0];
        var url = urlData[1];
        var urlLength = url.length;
        processNextChars(startIndex - idx);
        assem.append('\\url{');
        processNextChars(urlLength);
        assem.append('}');
      });
}`

So why is this implemented and how can I switch it off to get a proper export following the rules from the cheatsheet?

**Comment by JohnMcLear** [comment]
Fixed.
