### ISSUE TITLE
creation of locales to help to translate

### ISSUE THREAD

**Issue by PhilLAL** [ether/ep_markdown#23]
Hi,
I would like to help to translate this plugin.
Is it possible to add locale files to contribute?

For french, "Show markdown" would be translated into "Afficher en markdown".
Thank you.

**Comment by PhilLAL** [comment]
up in case this issue has been missed :)

**Comment by JohnMcLear** [comment]
Literally 2 lines..

https://github.com/ether/ep_markdown/commit/cd6eb6f133efa510937363558b25401101b58576

Feel free to create other edits and translations 🗡

**Comment by PhilLAL** [comment]
Thank you!
This translation is in french (fr) and not in german (de) but I will read this part. :)

**Comment by JohnMcLear** [comment]
Great thanks :)
