### ISSUE TITLE
Be able to import markdown

### ISSUE THREAD

**Issue by dessalines** [ether/ep_markdown#25]
I can copy paste the raw markdown, but then the headings / bullet points aren't preserved. Is there a good way to import markdown?

**Comment by JohnMcLear** [comment]
It appears not.  I made good markdown and put it in the browser then tried to copy to Etherpad and it all just becomes a mess..

```

   * Hello
   * world
# Header

``code``

``sdfsdflkj lksjd flkj sdf``

nolist

# derp
```

Is my example.

**Comment by JohnMcLear** [comment]
All done :)  Copy/paste is flakey but import is relatively stable.  Enjoy!
