### ISSUE TITLE
Manually entering markdown formats does not behave as expected

### ISSUE THREAD

**Issue by cetra3** [ether/ep_markdown#4]
If I manually enter in markdown formatting elements, they don't have the styling applied.  For instance, if i paste in markdown from an external source, the styling is not applied correctly.

![ep_markdown_issue](https://cloud.githubusercontent.com/assets/6415435/3836637/29fcc3fc-1dd9-11e4-82ee-d2e64c2e05ab.gif)

**Comment by JohnMcLear** [comment]
@cetra3 @madeofpeople you guys still wanna see this taking into account previous comment?

**Comment by cetra3** [comment]
Since I wrote the initial comment I do concur it'd be a substantial amount of work.

One thought I had was send the server the raw markdown and style it client side.  This would mean that you would not be using "rich input" at all, but a virtual version.  In order to do that though, you'd need to do a few things:

  1. Convert the pad to automatically convert things from markdown into html
  2. Hook all of the style toolbar options to produce markdown instead of html
  3. Send the markdown to the server instead of html

I'm not sure how complex that'd be to be honest, but I think it's probably the best shot.  I don't think @JohnMcLear should be the only one collaborating on this though, should be a bit of a group effort, since it will cause a lot of pain.

**Comment by madeofpeople** [comment]
@JohnMcLear I still think it would be pretty magical.
But I understand how much of a PITA this woul be. 

Is there no clear way to say "escape" ** when its desired?

Perhaps incorporating a dual-pane editor (raw on one side, parsed on the other ) or a view toggle... is a more direct and broadly-useful solution?
There are a bunch out there... this one's a simple jquery plugin (havent tested it) https://github.com/cbroome/markdownEditor

But don't let my not unfounded desires, scope creep on your plugin.

I've been getting into some ep plugin development over the last few months and hope to contribute something useful in the future.

**Comment by rikai** [comment]
I'd just like to express my interest for this particular feature.

This would bring etherpad 90% of the way to being a solution for a use case we've been looking to solve at my job for a while, a real-time collaborative editor that has full markdown support and can be edited in either markdown or rich-text mode simultaneously for people with varying degrees of markdown understanding.

As a note, the dual-pane mode mentioned in the previous comment is something fairly common to markdown editors to show a live preview, though i'm not sure how doable it would be in the case of etherpad.

**Comment by freemandealer** [comment]
Really looking forward to this feature. I guess then I can throw away my other Markdown editors.

**Comment by cetra3** [comment]
In the interim, I have found this project https://github.com/hackmdio/hackmd/

**Comment by dessalines** [comment]
This is a must for me.

**Comment by JohnMcLear** [comment]
I'm not really sure this makes sense to have this future within the scope of this project.  I think it would be something like ep_markdown_preview where you can still edit in real time on the left and preview on the right.  I'm pretty sure I made something like that once and if people want that functionality they should go with that.
